using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Migracion.Clases
{
    public class t_config5
    {
        public string dir_serv { get; set; }
        public DateTime fech_bpos { get; set; }
        public string bodega { get; set; }
        public string cod_pos { get; set; }
        public int empresa { get; set; }
        public int crea_anex { get; set; }
        public string sucursal { get; set; }
        public int tipo_fecha { get; set; }
        public DateTime fecha_doc { get; set; }
        public string docum_fac { get; set; }
        public string docum_dev { get; set; }
        public int fact_act { get; set; }
        public int devo_act { get; set; }
        public string docum_otr { get; set; }
        public int otros_act { get; set; }
        public string mens1 { get; set; }
        public string mens2 { get; set; }
        public int transac { get; set; }
        public DateTime fec_inip { get; set; }
        public int fact_cxc { get; set; }
        public int si_bajar { get; set; }
        public DateTime uavisofc { get; set; }
        public DateTime uavisodv { get; set; }
        public int si_bodega { get; set; }
        public int cerr_grab { get; set; }
        public int interv_cie { get; set; }
        public int preg_prec { get; set; }
        public int pide_cant { get; set; }
        public int pide_desc { get; set; }
        public int si_descgen { get; set; }
        public string fp_pred1 { get; set; }
        public string fp_pred2 { get; set; }
        public DateTime ult_cierre { get; set; }
        public int sin_busi { get; set; }
        public string ccosto { get; set; }
        public string cod_cash { get; set; }
        public string cod_papel { get; set; }
        public int win_fil0 { get; set; }
        public int win_col0 { get; set; }
        public int precio_up { get; set; }
        public int ayu_enter { get; set; }
        public int fec_local { get; set; }
        public int espac_tit1 { get; set; }
        public int n_lineblan { get; set; }
        public DateTime ult_expor { get; set; }
        public int deci_puni { get; set; }
        public int si_fac_dev { get; set; }
        public int items_red { get; set; }
        public int items_add { get; set; }
        public int win_exit { get; set; }
        public int grab_ent { get; set; }
        public int scale_com { get; set; }
        public string scale_set { get; set; }
        public string scale_code { get; set; }
        public string bmp_fondo { get; set; }
        public int si_dde { get; set; }
        public string serv_dde { get; set; }
        public string categdde { get; set; }
        public string comandde { get; set; }
        public int ocultabar { get; set; }
        public int ver_help { get; set; }
        public string exe_dde { get; set; }
        public int deci_det { get; set; }
        public int si_copyto { get; set; }
        public int si_dde_2 { get; set; }
        public int camara_com { get; set; }
        public int egres_act { get; set; }
        public string docum_egr { get; set; }
        public string datafono { get; set; }
        public int asadero { get; set; }
        public string fpago_asa { get; set; }
        public int sidomicil { get; set; }
        public int si_driver { get; set; }
        public string tef_port { get; set; }
        public int tef_veloc { get; set; }
        public string tef_parid { get; set; }
        public string tef_bitdat { get; set; }
        public string tef_stop { get; set; }
        public int tef_buffer { get; set; }
        public int tef_time { get; set; }
        public int tef_silen { get; set; }
        public string tef_exe { get; set; }
        public int tef_activo { get; set; }
        public int tipo_scale { get; set; }
        public int impr_elect { get; set; }
        public int num_copias { get; set; }
        public int no_act_ccq { get; set; }
        public string dat_banco { get; set; }
        public string docum_rcj { get; set; }
        public int rcj_act { get; set; }
        public int erro_pos { get; set; }
        public string dat_cnb { get; set; }
        public int ver_agota { get; set; }
        public int esdomicil { get; set; }
        public string tef_solic { get; set; }
        public string tef_respu { get; set; }
        public int tef_timew { get; set; }
        public string tef_dir { get; set; }
        public int tip_imp { get; set; }
        public string nom_print { get; set; }
        public int actqcre { get; set; }
        public int usaurano { get; set; }
        public int tipobal { get; set; }
        public int tef_sicaj { get; set; }
        public string tef_vret { get; set; }
        public DateTime fopeposl { get; set; }
        public int mod_teff { get; set; }
        public int si_runteff { get; set; }
        public int si_esp { get; set; }
        public int portcalif { get; set; }
        public int ultfact { get; set; }
        public int si_parq { get; set; }
        public string rut_calif { get; set; }
        public string dir_orig { get; set; }
        public string dir_dest { get; set; }
        public string ip_files { get; set; }
        public string ip_servi { get; set; }
        public string navegador { get; set; }
        public string rcconsult { get; set; }
        public DateTime fechaaper { get; set; }
        public int claveaper { get; set; }
        public string modoaper { get; set; }
        public int lmte_aper { get; set; }
        public int img_seg { get; set; }
        public int si_consult { get; set; }
        public string cod_tur { get; set; }
        public int lim_fesp { get; set; }
        public int si_facele { get; set; }
        public string docum_fel { get; set; }
        public int fele_act { get; set; }
        public int si_comanda { get; set; }
        public string comprinter { get; set; }
        public int facele_seg { get; set; }
        public int print_adv { get; set; }
        public int si_prompt { get; set; }
        public string cuc { get; set; }
        public int dc_act { get; set; }
        public string docum_dc { get; set; }
        public int estan_park { get; set; }
        public int ex_park { get; set; }
        public int ms2430 { get; set; }
        public int nuevocred { get; set; }
        public string pscale { get; set; }
        public string pscanner { get; set; }
        public int si_conti { get; set; }
        public int si_img_pos { get; set; }
        public int si_merma { get; set; }
        public int si_showres { get; set; }
        public int time_2430 { get; set; }
        public string vscale { get; set; }
        public string vscanner { get; set; }
        public int borrain { get; set; }
        public string escucha { get; set; }
        public string flujou { get; set; }
        public string log_tef { get; set; }
        public string previa { get; set; }
        public int tef_v924 { get; set; }
        public string tiporta { get; set; }
        public string provfe { get; set; }
        public DateTime fechaprov { get; set; }
        public int coptabfele { get; set; }

    }
}
