using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Migracion.Clases
{
    internal class t_config
    {
        public string reg_iva { get; set; }
        public int gran_con { get; set; }
        public string gran_conr { get; set; }
        public DateTime gran_conf { get; set; }
        public int ret_iva { get; set; }
        public string ret_ivar { get; set; }
        public DateTime ret_ivaf { get; set; }
        public int claseper { get; set; }
        public int autorr { get; set; }
        public string autorr_r { get; set; }
        public DateTime autorr_f { get; set; }
        public int nivelmyb { get; set; }
        public DateTime fech_sldoi { get; set; }
        public int inv_rojo { get; set; }
        public int tipo_inv { get; set; }
        public string bode_omi { get; set; }
        public string vend_omi { get; set; }
        public string zona_omi { get; set; }
        public string cco_omi { get; set; }
        public int terc_omi { get; set; }
        public string sucu_omi { get; set; }
        public int modo_rent { get; set; }
        public int dias_ven { get; set; }
        public int borr_anu { get; set; }
        public int boni_com { get; set; }
        public int boni_vta { get; set; }
        public int manej_suc { get; set; }
        public int manej_cco { get; set; }
        public int terc_inac { get; set; }
        public int ctas_inac { get; set; }
        public int item_inac { get; set; }
        public int docu_inac { get; set; }
        public int ref_cons { get; set; }
        public int cost_inv { get; set; }
        public int iva_gen { get; set; }
        public string cod_rflet { get; set; }
        public string n_ite1 { get; set; }
        public string n_ite2 { get; set; }
        public string n_ite3 { get; set; }
        public string n_ite4 { get; set; }
        public string n_ite5 { get; set; }
        public string n_ite6 { get; set; }
        public string n_ite7 { get; set; }
        public string n_ite8 { get; set; }
        public string n_ite9 { get; set; }
        public string n_ite10 { get; set; }
        public string n_ane1 { get; set; }
        public string n_ane2 { get; set; }
        public string n_ane3 { get; set; }
        public string n_ane4 { get; set; }
        public string n_ane5 { get; set; }
        public string n_ane6 { get; set; }
        public string n_ane7 { get; set; }
        public int manej_mar { get; set; }
        public string marca_omi { get; set; }
        public string nomb_rl { get; set; }
        public string carg_rl { get; set; }
        public string cc_rl { get; set; }
        public string nomb_rf { get; set; }
        public string mat_rf { get; set; }
        public string cc_rf { get; set; }
        public string no_cierra { get; set; }
        public int mod_p1 { get; set; }
        public int mod_p2 { get; set; }
        public int mod_p3 { get; set; }
        public int mod_pp { get; set; }
        public string retf_omi { get; set; }
        public string grup_omi { get; set; }
        public int nit_trans { get; set; }
        public int ver_spr { get; set; }
        public int si_codbar { get; set; }
        public int act_crep { get; set; }
        public int si_retfte { get; set; }
        public int tipo_myb { get; set; }
        public int si_iva { get; set; }
        public int sdo_signo { get; set; }
        public int niv3_lin { get; set; }
        public int niv4_lin { get; set; }
        public int anex_bce { get; set; }
        public int ver_refer { get; set; }
        public int comis_30 { get; set; }
        public int comis_60 { get; set; }
        public int comis_90 { get; set; }
        public int no_eject { get; set; }
        public int signopos { get; set; }
        public int si_ciudad { get; set; }
        public string basefpos { get; set; }
        public string basedpos { get; set; }
        public int tipo_help { get; set; }
        public int pos_lineas { get; set; }
        public int buscaxnit { get; set; }
        public int modicost { get; set; }
        public int modipvan { get; set; }
        public int ult_anex { get; set; }
        public string dirnet_gen { get; set; }
        public string fp_mercap { get; set; }
        public string aprobkeymp { get; set; }
        public int tc_activa { get; set; }
        public string dirnet_pos { get; set; }
        public int si_bonosl { get; set; }
        public int mpmessage1 { get; set; }
        public int no_wan { get; set; }
        public int diasvenbon { get; set; }
        public DateTime ultciepos { get; set; }
        public string doc_trasl { get; set; }
        public int domic_lim { get; set; }
        public int domic_vlr { get; set; }
        public string dirnet_bon { get; set; }
        public int emite_bon { get; set; }
        public int desco_dias { get; set; }
        public int tasaimfa { get; set; }
        public int cuotaminfa { get; set; }
        public int ncuotasfa { get; set; }
        public int ivafin_fa { get; set; }
        public int finanmaxfa { get; set; }
        public int vr_comisop { get; set; }
        public int ivacomisop { get; set; }
        public int no_cedula { get; set; }
        public int suc_princi { get; set; }
        public int ica_aviso1 { get; set; }
        public int ica_aviso2 { get; set; }
        public int ica_bomb1 { get; set; }
        public int ica_bomb2 { get; set; }
        public string codicaciud { get; set; }
        public string cta_ica1 { get; set; }
        public string cta_ica2 { get; set; }
        public string cta_ica3 { get; set; }
        public int no_descod { get; set; }
        public int mp_tiempo { get; set; }
        public int mp_tiempo2 { get; set; }
        public string mp_fondo1 { get; set; }
        public string mp_fondo2 { get; set; }
        public int ver_venci { get; set; }
        public int anno_venci { get; set; }
        public int activ_venc { get; set; }
        public int egbonini { get; set; }
        public DateTime fe_ini_out { get; set; }
        public DateTime fe_fin_out { get; set; }
        public int fe_act_out { get; set; }
        public int egbonfin { get; set; }
        public DateTime fn_ini_out { get; set; }
        public DateTime fn_fin_out { get; set; }
        public int fn_act_out { get; set; }
        public string frx_prorr { get; set; }
        public string frx_preav { get; set; }
        public string frx_reti { get; set; }
        public string frx_certif { get; set; }
        public string frx_cesan { get; set; }
        public string frx_exam { get; set; }
        public int si_vencim { get; set; }
        public int dias_venci { get; set; }
        public string arpdefault { get; set; }
        public string dane_nomi { get; set; }
        public int codigo_ct { get; set; }
        public int cupoq1_ini { get; set; }
        public int cupoq1_fin { get; set; }
        public int cupoq2_ini { get; set; }
        public int cupoq2_fin { get; set; }
        public string mpreposi { get; set; }
        public string impr_docum { get; set; }
        public int activrepos { get; set; }
        public string aut_tarjet { get; set; }
        public string cod_prest { get; set; }
        public int rut_regcom { get; set; }
        public int maxcuotemp { get; set; }
        public int prov_ces { get; set; }
        public int prov_pri { get; set; }
        public int prov_vac { get; set; }
        public int comifinfn { get; set; }
        public int comifinfn1 { get; set; }
        public int comifinfn2 { get; set; }
        public int comifinfn3 { get; set; }
        public int ivacomifn { get; set; }
        public int ivacomifn1 { get; set; }
        public int ivacomifn2 { get; set; }
        public int ivacomifn3 { get; set; }
        public int facsegvida { get; set; }
        public string doc_comp { get; set; }
        public int bloq_ord { get; set; }
        public int val_aut { get; set; }
        public int usa_tarjes { get; set; }
        public int anul_clien { get; set; }
        public int comifinfn4 { get; set; }
        public int ivacomifn4 { get; set; }
        public int n_cheqenv { get; set; }
        public string aprokeyrcj { get; set; }
        public string basercpos { get; set; }
        public int fvenregal { get; set; }
        public DateTime bloqueo_fp { get; set; }
        public int si_infcump { get; set; }
        public string cnb_xc { get; set; }
        public string cnb_xp { get; set; }
        public string docum_cnb { get; set; }
        public int fe_cuo_out { get; set; }
        public DateTime fe_ini_ou2 { get; set; }
        public DateTime fe_fin_ou2 { get; set; }
        public int fe_act_ou2 { get; set; }
        public int fn_cuo_out { get; set; }
        public DateTime fn_ini_ou2 { get; set; }
        public DateTime fn_fin_ou2 { get; set; }
        public int fn_act_ou2 { get; set; }
        public int numdig { get; set; }
        public int limdig { get; set; }
        public DateTime fecdig { get; set; }
        public string dirnet_fir { get; set; }
        public string doc_ped { get; set; }
        public string codicaom { get; set; }
        public int lmte_exc { get; set; }
        public int lmte_dia { get; set; }
        public string bod_desp { get; set; }
        public DateTime fopeposs { get; set; }
        public int valvisad { get; set; }
        public string dir_rut { get; set; }
        public string docdevprov { get; set; }
        public int act_fs { get; set; }
        public int ord_dia { get; set; }
        public string fpdestcm { get; set; }
        public int desmaxtcm { get; set; }
        public int dcttcmer { get; set; }
        public string doccint { get; set; }
        public string doc_tras { get; set; }
        public string doc_notd { get; set; }
        public string glnprin { get; set; }
        public int impbolsa { get; set; }
        public int valimpbo { get; set; }
        public string docintem { get; set; }
        public int ico_gen { get; set; }
        public string docimpor { get; set; }
        public int aju_impb { get; set; }
        public string codajuimb { get; set; }
        public int valajufac { get; set; }
        public int valdifcj { get; set; }
        public string doc_ajuef { get; set; }
        public DateTime fechaaper { get; set; }
        public int claveaper { get; set; }
        public int lmte_aper { get; set; }
        public int vtamendeno { get; set; }
        public string anno_log { get; set; }
        public string p_log { get; set; }
        public int si_icogen { get; set; }
        public int valdsiva { get; set; }
        public int diascreg { get; set; }
        public int diamaxdes { get; set; }

    }
}
